INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Cup');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Pinch');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Ounce');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Each');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Dash');
INSERT INTO unit_of_measure (UNIT_OF_MEASURE ) VALUES ('Pint');